# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/about_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_about(object):
    def setupUi(self, dialog_about):
        dialog_about.setObjectName("dialog_about")
        dialog_about.resize(722, 594)
        self.label = QtWidgets.QLabel(dialog_about)
        self.label.setGeometry(QtCore.QRect(10, 0, 701, 411))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.push_openNDFManual = QtWidgets.QPushButton(dialog_about)
        self.push_openNDFManual.setGeometry(QtCore.QRect(10, 420, 161, 23))
        self.push_openNDFManual.setObjectName("push_openNDFManual")
        self.label_2 = QtWidgets.QLabel(dialog_about)
        self.label_2.setGeometry(QtCore.QRect(10, 450, 591, 101))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(dialog_about)
        QtCore.QMetaObject.connectSlotsByName(dialog_about)

    def retranslateUi(self, dialog_about):
        _translate = QtCore.QCoreApplication.translate
        dialog_about.setWindowTitle(_translate("dialog_about", "About"))
        self.label.setText(_translate("dialog_about", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">IDF Viewer 1.0b (Beta version)</span></p><p>October 2021</p><p>Created by Miguel Sequeira</p><p>For reporting bugs or give feedback please send an e-mail to: <a href=\"mailto:miguel.sequeira@tecnico.ulisboa.pt?subject=[IDF Viewer]\"><span style=\" text-decoration: underline; color:#0000ff;\">miguel.sequeira@tecnico.ulisboa.pt</span></a></p><p>Please start the subject with &quot;[IDF Viewer]&quot;.</p><p>In case of a bug, include:</p><p>- the OS system;</p><p>- the steps to reproduce the bug;</p><p>- the files used if applicable;</p><p>- and of course, any other information that you might find helpful.</p><p><br/></p><p><span style=\" font-size:10pt; font-weight:600;\">NDF Version 11.0b (IDF Beta version)</span></p><p>October 2021</p><p>Created by Nuno Pessoa Barradas, updated by Miguel Sequeira (IDF integration)</p></body></html>"))
        self.push_openNDFManual.setText(_translate("dialog_about", "Open NDF Manual"))
        self.label_2.setText(_translate("dialog_about", "<html><head/><body><p>Refer to: </p><p>- N.P.Barradas, C. Jeynes, R.P. Webb, Appl. Phys. Lett. 71 (1997) 291</p><p>- C. Jeynes, N.P. Barradas, P.K. Marriott, M. Jenkin, E. Wendler, G. Boudreault, R.P. Webb,</p><p>J. Phys. D: Appl. Phys. 36 (2003) R97-R126 (Topical Review).</p></body></html>"))
