# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/about_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_about(object):
    def setupUi(self, dialog_about):
        dialog_about.setObjectName("dialog_about")
        dialog_about.resize(465, 910)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog_about.sizePolicy().hasHeightForWidth())
        dialog_about.setSizePolicy(sizePolicy)
        dialog_about.setMinimumSize(QtCore.QSize(465, 910))
        dialog_about.setMaximumSize(QtCore.QSize(465, 910))
        dialog_about.setAutoFillBackground(True)
        dialog_about.setStyleSheet("")
        self.label = QtWidgets.QLabel(dialog_about)
        self.label.setGeometry(QtCore.QRect(35, 410, 481, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.push_openNDFManual = QtWidgets.QPushButton(dialog_about)
        self.push_openNDFManual.setGeometry(QtCore.QRect(160, 730, 131, 23))
        self.push_openNDFManual.setObjectName("push_openNDFManual")
        self.label_2 = QtWidgets.QLabel(dialog_about)
        self.label_2.setGeometry(QtCore.QRect(34, 770, 431, 121))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_logo = QtWidgets.QLabel(dialog_about)
        self.label_logo.setGeometry(QtCore.QRect(28, -70, 861, 481))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("logos/icon_text_nobackground.png"))
        self.label_logo.setObjectName("label_logo")
        self.label_4 = QtWidgets.QLabel(dialog_about)
        self.label_4.setGeometry(QtCore.QRect(40, 640, 381, 91))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(dialog_about)
        self.line.setGeometry(QtCore.QRect(20, 630, 421, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(dialog_about)
        self.label_5.setGeometry(QtCore.QRect(35, 350, 381, 61))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(dialog_about)
        QtCore.QMetaObject.connectSlotsByName(dialog_about)

    def retranslateUi(self, dialog_about):
        _translate = QtCore.QCoreApplication.translate
        dialog_about.setWindowTitle(_translate("dialog_about", "About"))
        self.label.setText(_translate("dialog_about", "<html><head/><body><p><span style=\" font-size:10pt;\">For reporting bugs or give feedback please send an e-mail to: </span><a href=\"mailto:miguel.sequeira@tecnico.ulisboa.pt?subject=[IDF Viewer]\"><span style=\" font-size:10pt; text-decoration: underline; color:#0000ff;\">miguel.sequeira@tecnico.ulisboa.pt</span></a></p><p><span style=\" font-size:10pt;\">Please start the subject with &quot;[IBA Studio]&quot;.</span></p><p><span style=\" font-size:10pt;\">In case of a bug, include:</span></p><p><span style=\" font-size:10pt;\">- the OS system;</span></p><p><span style=\" font-size:10pt;\">- the steps to reproduce the bug;</span></p><p><span style=\" font-size:10pt;\">- the files used if applicable;</span></p><p><span style=\" font-size:10pt;\">- the IBAStudio_run.log file in the IBAStudio folder</span></p></body></html>"))
        self.push_openNDFManual.setText(_translate("dialog_about", "NDF Manual..."))
        self.label_2.setText(_translate("dialog_about", "<html><head/><body><p><span style=\" font-size:10pt;\">Refer to: </span></p><p><span style=\" font-size:10pt;\">- N.P.Barradas, C. Jeynes, R.P. Webb, Appl. Phys. Lett. 71 (1997) 291</span></p><p><span style=\" font-size:10pt;\">- C. Jeynes, N.P. Barradas, P.K. Marriott, M. Jenkin, E. Wendler, G. Boudreault, R.P. Webb,</span></p><p><span style=\" font-size:10pt;\">J. Phys. D: Appl. Phys. 36 (2003) R97-R126 (Topical Review).</span></p></body></html>"))
        self.label_4.setText(_translate("dialog_about", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">NDF Version 11.0b (IDF Beta)</span></p><p align=\"center\">October 2021, Nuno Pessoa Barradas (core), Miguel Sequeira (IDF integration)</p></body></html>"))
        self.label_5.setText(_translate("dialog_about", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IBA Studio 1.0b (Beta)</span></p><p align=\"center\">June 2023, Miguel Sequeira</p></body></html>"))
